### ISSUE TITLE
Remove date from home

### ISSUE THREAD

**Issue by vitorsouzaalmeida** [vitorsouzaalmeida/blog#157]
![image](https://user-images.githubusercontent.com/70543018/172465009-ade45da5-4bbc-4bd8-8893-5fcee4622e42.png)

Without the date looks better... Now I need to think some new place to show the date

**Comment by vitorsouzaalmeida** [comment]
Or remove the date for at all? i don't know

**Comment by biantris** [comment]
Dates are nice, they help me to know how up to date what I'm reading is, the dates can be under the title of the texts, what do you think?
![image](https://user-images.githubusercontent.com/65451957/172466421-9eaedb83-c870-4803-8f4f-27bbd554ba5c.png)

**Comment by biantris** [comment]
oh it seems ok to me already \o/
![image](https://user-images.githubusercontent.com/65451957/172466623-0dc9af9b-fb90-4bdc-aff2-7208c62c03c0.png)

**Comment by vitorsouzaalmeida** [comment]
Yeap,
I can remove only in the Home screen. - Home screen show only the last five articles
Inside of my articles and in the [Blog](https://vitorsalmeida.com/blog) page, I keep the same.

![image](https://user-images.githubusercontent.com/70543018/172481745-fb57bc0c-951d-4742-af0b-0cb2a233888f.png)

**Comment by vitorsouzaalmeida** [comment]
@biantris 
![image](https://user-images.githubusercontent.com/70543018/172483234-0926c892-da7f-464e-abb2-da655d482442.png)

**Comment by biantris** [comment]
> @biantris ![image](https://user-images.githubusercontent.com/70543018/172483234-0926c892-da7f-464e-abb2-da655d482442.png)

It looks good to me 👍
