### ISSUE TITLE
Fix ref. link easy-life-making-excuses

### ISSUE THREAD

**Issue by vitorsouzaalmeida** [vitorsouzaalmeida/blog#194]
https://vitorsalmeida.com/blog/en/easy-life-making-excuses

"Read [Lessons learned in my first English interview](https://vitorsalmeida.com/blog/my-first-english-interview) to understand."

Should redirect to https://vitorsalmeida.com/blog/en/my-first-english-interview

https://github.com/vit0rr/portfolio/blob/1472bae7204e1d4a6d7763be58d1c7fb7b69e428/data/blog/en/easy-life-making-excuses.md#L22

**Comment by aldair-meneses** [comment]
Done it in #195
